
@HostAddress = https://localhost:7258


GET {{HostAddress}}/products

###

POST {{HostAddress }}/products
Content-Type: application/json
{
   "name":"Ürün  A",
   "price":17,
   "imageUrl":"sample.png",
   "categoryId":1
}
###
