@minimalAPIs_HostAddress = https://localhost:7292


POST {{minimalAPIs_HostAddress}}/products
Content-Type:application/json
{
  "name":"test product 2",
  "price":15
}

###

GET {{minimalAPIs_HostAddress}}/products

###

GET {{minimalAPIs_HostAddress}}/products/1

###

PUT {{minimalAPIs_HostAddress}}/products/1
Content-Type:application/json
{
  "id": 1,
  "name":"Deneme",
  "price":350
}
###

DELETE {{minimalAPIs_HostAddress}}/products/1

###
